/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
open class App {
    val greeting: String = "Hello World!"
}

fun main() {
    runApplication<App>()
}
